name: mock_interviewer
description: "A new Flutter project."
publish_to: 'none' 
version: 1.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.4.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.2
  firebase_remote_config: ^5.0.4
  flutter_markdown: ^0.7.3
  cloud_firestore: ^5.2.0
  camera: ^0.11.0+2
  flutter_tts: ^4.0.2
  url_launcher: ^6.3.0
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/interview.png
    - assets/icons/dart.png
    - assets/icons/flutter.png
    - assets/icons/curly.png
    - assets/icons/kotlin.png
    - assets/icons/android.png
