// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8hXgRTVg89oaYMKcMs-1w80xW8J9RyvA',
    appId: '1:677972614013:web:8b1c01582e7cc8220bca14',
    messagingSenderId: '677972614013',
    projectId: 'mock-interviewer-29bc5',
    authDomain: 'mock-interviewer-29bc5.firebaseapp.com',
    storageBucket: 'mock-interviewer-29bc5.appspot.com',
    measurementId: 'G-HRG88G7NCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-kkJxkSleznruxaFTxYkrxXSRnFAkBU',
    appId: '1:677972614013:android:264a5f75258718be0bca14',
    messagingSenderId: '677972614013',
    projectId: 'mock-interviewer-29bc5',
    storageBucket: 'mock-interviewer-29bc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0e3hO-Btq8QD8H_5KSwq7xB253NiVOk0',
    appId: '1:677972614013:ios:49b9da7d6c031a660bca14',
    messagingSenderId: '677972614013',
    projectId: 'mock-interviewer-29bc5',
    storageBucket: 'mock-interviewer-29bc5.appspot.com',
    iosBundleId: 'com.example.mockInterviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0e3hO-Btq8QD8H_5KSwq7xB253NiVOk0',
    appId: '1:677972614013:ios:49b9da7d6c031a660bca14',
    messagingSenderId: '677972614013',
    projectId: 'mock-interviewer-29bc5',
    storageBucket: 'mock-interviewer-29bc5.appspot.com',
    iosBundleId: 'com.example.mockInterviewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8hXgRTVg89oaYMKcMs-1w80xW8J9RyvA',
    appId: '1:677972614013:web:6cc7d598d5c0dcaf0bca14',
    messagingSenderId: '677972614013',
    projectId: 'mock-interviewer-29bc5',
    authDomain: 'mock-interviewer-29bc5.firebaseapp.com',
    storageBucket: 'mock-interviewer-29bc5.appspot.com',
    measurementId: 'G-9PBQTX5HQW',
  );
}
